debug: false
num_workers: 8
seed: 0
n_epochs: 100
batch_size: 64
ckp_path: '../checkpoint/'
data_path: '../../../TAU-urban-audio-visual-scenes-2021-development/'


video_clip_duration: 10
video_fps: 16.
audio_fps: 16000
audio_dur: 10
spectrogram_fps: 100.
n_fft: 512
n_mels: 64
model_type: 'audio'

num_classes: 10
feat_name: "pool"
pooling_op: null
feat_dim: 512
use_dropout: true
dropout: 0.5