debug: False
num_workers: 16
seed: 0
n_epochs: 100
batch_size: 309
ckp_path: './checkpoint/'

vgg_path: '/vgg-sound/'
unwanted_files_path: '../unwanted.csv'

video_clip_duration: 0.5
video_fps: 16.
audio_fps: 16000
audio_dur: 1
spectrogram_fps: 100.
n_fft: 512
n_mels: 64
